import React from 'react';
import ReactMarkdown from 'react-markdown';

const StrategyModal = ({ isOpen, onClose, content }) => {
    if (!isOpen) return null;

    const handlePrint = () => {
        window.print();
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        // Could add a toast notification here
        alert("Report copied to clipboard!");
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
            <div className="bg-zinc-900 border border-white/10 rounded-2xl w-full max-w-4xl h-[90vh] flex flex-col shadow-2xl relative overflow-hidden">

                {/* Header */}
                <div className="flex justify-between items-center p-6 border-b border-white/5 bg-zinc-900/50 backdrop-blur-md">
                    <h2 className="text-xl font-light tracking-wide text-white">Strategy Report</h2>
                    <div className="flex gap-2">
                        <button
                            onClick={handleCopy}
                            className="px-4 py-2 text-xs uppercase tracking-widest text-zinc-400 hover:text-white border border-white/10 rounded-lg hover:bg-white/5 transition-all"
                        >
                            Copy
                        </button>
                        <button
                            onClick={handlePrint}
                            className="px-4 py-2 text-xs uppercase tracking-widest text-emerald-400 hover:text-emerald-300 border border-emerald-500/20 rounded-lg hover:bg-emerald-500/10 transition-all"
                        >
                            Print PDF
                        </button>
                        <button
                            onClick={onClose}
                            className="ml-2 p-2 text-zinc-500 hover:text-white transition-colors"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-8 custom-scrollbar bg-black/20">
                    <div className="prose prose-invert prose-sm max-w-none prose-headings:font-light prose-headings:tracking-wide prose-p:text-zinc-300 prose-li:text-zinc-300 prose-strong:text-white">
                        <ReactMarkdown>{content}</ReactMarkdown>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-white/5 bg-zinc-900/50 text-center text-[10px] text-zinc-500 uppercase tracking-widest">
                    Generated by Cerno AI
                </div>

                {/* Print Styles */}
                <style>{`
                    @media print {
                        body * {
                            visibility: hidden;
                        }
                        .fixed.inset-0.z-\\[100\\] {
                            position: absolute;
                            left: 0;
                            top: 0;
                            width: 100%;
                            height: 100%;
                            background: white;
                            color: black;
                            padding: 0;
                            margin: 0;
                            visibility: visible !important;
                            z-index: 9999;
                        }
                        .fixed.inset-0.z-\\[100\\] * {
                            visibility: visible !important;
                            color: black !important;
                        }
                        /* Hide buttons in print */
                        .fixed.inset-0.z-\\[100\\] button {
                            display: none !important;
                        }
                        /* Adjust text for print */
                        .prose {
                            color: black !important;
                        }
                    }
                `}</style>
            </div>
        </div>
    );
};

export default StrategyModal;
